In [1]:
import numpy as np
import pandas as pd

In [2]:
car_data=pd.read_csv('data.csv') #loading data

In [3]:
car_data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [26]:
# assigning independent and dependent variables
x=car_data.iloc[:,[12, 13, 14]].values
y=car_data.iloc[:,[15]].values
print(x)
print(y)

[[  26   19 3916]
 [  28   19 3916]
 [  28   20 3916]
 ...
 [  23   16  204]
 [  23   16  204]
 [  26   17   61]]
[[46135]
 [40650]
 [36350]
 ...
 [50620]
 [50920]
 [28995]]


In [22]:
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [27]:
train_x,val_x,train_y,val_y=train_test_split(x,y,test_size=0.25,random_state=0)#splitting data into train set and val set

In [24]:
car_model=RandomForestRegressor(random_state=0)

In [28]:
car_model.fit(train_x,train_y)#fitting the model for train data

D:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [29]:
val_predict=car_model.predict(val_x)#trained algo predicts the values for valset

In [30]:
val_mae=mean_absolute_error(val_predict,val_y)
print(val_mae)

8911.613958149104


In [35]:
print(val_predict[199])
print(val_y[199])

18683.333333333332
[18595]


In [36]:
# model accuracy using R-squared
from sklearn.metrics import r2_score
r2_score(val_y, val_predict)

0.8349087074349684